ruby/neighborhood_allies/config/routes.rb
Rails.application.routes.draw do

  get 'seed_gen/index'

post 'organizations/:id/showvectors/' => 'organizations#showvectors'
post 'orgadmins/:id/showorgconnections/' => 'orgadmins#showorgconnections'
post 'orgadmins/:id/addorgconnections/' => 'orgadmins#addorgconnections'

get 'organizations/:id/showvectors/' => 'organizations#showvectors'
get 'orgadmins/:id/showorgconnections/' => 'orgadmins#showorgconnections'
get 'orgadmins/:id/addorgconnections/' => 'orgadmins#addorgconnections'
resources :organizations
get 'organizations/:id/about' => 'organizations#about'

resources :orgadmins

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
resources :logos do
  get "serve", :on => :member
end

  root 'organizations#index_landing'

end

ruby/neighborhood_allies/app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :organization
end

ruby/neighborhood_allies/app/models/fund_cat_a.rb
class FundCatA < ActiveRecord::Base
    belongs_to :organization
    has_many :fund_cat_bs
end

ruby/neighborhood_allies/app/models/fund_cat_b.rb
class FundCatB < ActiveRecord::Base
    belongs_to :fund_cat_a
    has_many :fund_check_box
end

ruby/neighborhood_allies/app/models/fund_check_box.rb
class FundCheckBox < ActiveRecord::Base
    belongs_to :fund_cat_b
end

ruby/neighborhood_allies/app/models/funder.rb
class Funder < ActiveRecord::Base    
    has_many :organization
    has_many :fund_cat_as
end

ruby/neighborhood_allies/app/models/funding_sent.rb
class FundingSent < ActiveRecord::Base
  belongs_to :organization, :class_name => Organization
end

ruby/neighborhood_allies/app/models/funding_type.rb
class FundingType < ActiveRecord::Base
end

ruby/neighborhood_allies/app/models/logo.rb
class Logo < ActiveRecord::Base
    belongs_to :organization
end

ruby/neighborhood_allies/app/models/org_status.rb
class OrgStatus < ActiveRecord::Base
    belongs_to :organization
end

ruby/neighborhood_allies/app/models/org_status_other.rb
class OrgStatusOther < ActiveRecord::Base
end

ruby/neighborhood_allies/app/models/org_web_url.rb
class OrgWebUrl < ActiveRecord::Base
    belongs_to :organization
    has_one :social_type
end

ruby/neighborhood_allies/app/models/organization.rb
class Organization < ActiveRecord::Base
  has_and_belongs_to_many :funders
  has_many :org_web_urls
  has_one :logo
  has_one :p_ao_s
  has_one :budget
  has_one :staff_size
  has_one :org_status
  has_many :funding_sents, :foreign_key => "organization_id_sent"
  has_many :funding_receives, :foreign_key => "organization_id_received"

  def as_json(option={})
    super(:only => [:name, :phone, :email, :descrip, :mission, :address,],
          :include => {
            :funders =>{:only => [:name]
            }
          }
      )
  end
end

ruby/neighborhood_allies/app/models/p_ao_s.rb
class PAoS < ActiveRecord::Base
    belongs_to :organization
end

ruby/neighborhood_allies/app/models/p_ao_s_other.rb
class PAoSOther < ActiveRecord::Base
end

ruby/neighborhood_allies/app/models/social_type.rb
class SocialType < ActiveRecord::Base
    belongs_to :org_web_url
end

ruby/neighborhood_allies/app/models/staff_size.rb
class StaffSize < ActiveRecord::Base
  belongs_to :organization
end

ruby/neighborhood_allies/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

ruby/neighborhood_allies/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/neighborhood_allies/app/helpers/orgadmins_helper.rb
module OrgadminsHelper
end

ruby/neighborhood_allies/app/helpers/seed_gen_helper.rb
module SeedGenHelper
end

ruby/neighborhood_allies/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neighborhood Allies Mapping Project</title>

<!-- added by Ray -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>

</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
        <a class="navbar-brand" href="https://neighborhood-allies-uugengiven.c9users.io/">
      		 <img src="http://apps.pittsburghpa.gov/mayor/NeighborhoodAllies_Logo_Web_Large6-300x95.jpg"/>
        </a>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav" id="location">
          <li><a href="http://neighborhoodallies.com/" id="about-tag"><strong>ABOUT</strong></a></li>
    	    <li><a href="#" id="about-tag"><strong>NEWSLETTER</strong></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

							<% if !user_signed_in? %>
								<div id="whenSignedOut">
									<li><span class="glyphicon glyphicon-log-in" ></span><a href="#loginModal" data-toggle="modal" data-target="#loginModal" id="login">LOGIN</a></li>
								  <li><span class = "glyphicon glyphicon-pencil"></span><%= link_to 'REGISTER ORGANIZATION', new_organization_path %></li>
								</div>
							<% else %>
								<div>
								  <li><span class = "glyphicon glyphicon-pencil"></span><%= link_to 'Edit Organizations', orgadmins_path %></li>
								  <li><span class="glyphicon glyphicon-log-in" ></span><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
								</div>
							<% end %>
        </ul>
      </div>
    </div>
  </nav>
 
<%= yield %>

</body>
</html>