ruby/neighborhood_allies/config/routes.rb
Rails.application.routes.draw do

  get 'seed_gen/index'

post 'organizations/:id/showvectors/' => 'organizations#showvectors'
post 'orgadmins/:id/showorgconnections/' => 'orgadmins#showorgconnections'
post 'orgadmins/:id/addorgconnections/' => 'orgadmins#addorgconnections'

get 'organizations/:id/showvectors/' => 'organizations#showvectors'
get 'orgadmins/:id/showorgconnections/' => 'orgadmins#showorgconnections'
get 'orgadmins/:id/addorgconnections/' => 'orgadmins#addorgconnections'
resources :organizations
get 'organizations/:id/about' => 'organizations#about'

resources :orgadmins

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
resources :logos do
  get "serve", :on => :member
end

  root 'organizations#index_landing'

end

ruby/neighborhood_allies/app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :organization
end

ruby/neighborhood_allies/app/models/fund_cat_a.rb
class FundCatA < ActiveRecord::Base
    belongs_to :organization
    has_many :fund_cat_bs
end

ruby/neighborhood_allies/app/models/fund_cat_b.rb
class FundCatB < ActiveRecord::Base
    belongs_to :fund_cat_a
    has_many :fund_check_box
end

ruby/neighborhood_allies/app/models/fund_check_box.rb
class FundCheckBox < ActiveRecord::Base
    belongs_to :fund_cat_b
end

ruby/neighborhood_allies/app/models/funder.rb
class Funder < ActiveRecord::Base    
    has_many :organization
    has_many :fund_cat_as
end

ruby/neighborhood_allies/app/models/funding_sent.rb
class FundingSent < ActiveRecord::Base
  belongs_to :organization, :class_name => Organization
end

ruby/neighborhood_allies/app/models/funding_type.rb
class FundingType < ActiveRecord::Base
end

ruby/neighborhood_allies/app/models/logo.rb
class Logo < ActiveRecord::Base
    belongs_to :organization
end

ruby/neighborhood_allies/app/models/org_status.rb
class OrgStatus < ActiveRecord::Base
    belongs_to :organization
end

ruby/neighborhood_allies/app/models/org_status_other.rb
class OrgStatusOther < ActiveRecord::Base
end

ruby/neighborhood_allies/app/models/org_web_url.rb
class OrgWebUrl < ActiveRecord::Base
    belongs_to :organization
    has_one :social_type
end

ruby/neighborhood_allies/app/models/organization.rb
class Organization < ActiveRecord::Base
  has_and_belongs_to_many :funders
  has_many :org_web_urls
  has_one :logo
  has_one :p_ao_s
  has_one :budget
  has_one :staff_size
  has_one :org_status
  has_many :funding_sents, :foreign_key => "organization_id_sent"
  has_many :funding_receives, :foreign_key => "organization_id_received"

  def as_json(option={})
    super(:only => [:name, :phone, :email, :descrip, :mission, :address,],
          :include => {
            :funders =>{:only => [:name]
            }
          }
      )
  end
end

ruby/neighborhood_allies/app/models/p_ao_s.rb
class PAoS < ActiveRecord::Base
    belongs_to :organization
end

ruby/neighborhood_allies/app/models/p_ao_s_other.rb
class PAoSOther < ActiveRecord::Base
end

ruby/neighborhood_allies/app/models/social_type.rb
class SocialType < ActiveRecord::Base
    belongs_to :org_web_url
end

ruby/neighborhood_allies/app/models/staff_size.rb
class StaffSize < ActiveRecord::Base
  belongs_to :organization
end

ruby/neighborhood_allies/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

ruby/neighborhood_allies/app/controllers/logos_controller.rb
class LogosController < ApplicationController
protect_from_forgery :except => [:update, :delete, :create]

  def index
    @logos = Logo.all

  end

  def show
  end

  def new
    @logo = Logo.new
    @orgs = Organization.all
  end

  def create
   puts "l"
   
   @logo = Logo.new()
   @logo.name = params[:name]
   @logo.organization_id = params[:organization_id]
   if params[:logo][:data]
     @logo.data = params[:logo][:data].read
     @logo.filename = params[:logo][:data].original_filename
     @logo.mime_type = params[:logo][:data].content_type
   end
     #normal save
    if @logo.save
      redirect_to(@logo, :notice => "Successfully Posted Photo")
    else
      render :action => "new"
    end
  end
 
  def serve
    @logo = Logo.find_by(:organization_id => params[:id])
    if @logo.nil?
      @logo = Logo.find(1);
    end
    send_data(@logo.data, :type => @logo.mime_type, :filename => "#{@logo.name}.jpg", :disposition => "inline")
  end
  
  def destroy
    @logo = Photo.find(params[:id])
    @logo.destroy
    redirect_to(photos_url)
  end
  
  private
    def user_params
      params.require(:logo).permit(:name, :data, :filename,:mime_type)
    end
  
end

ruby/neighborhood_allies/app/controllers/orgadmins_controller.rb
class OrgadminsController < ApplicationController
  before_action :set_orgadmin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /orgadmins
  # GET /orgadmins.json
  def index
    @organizations = Organization.all
  end

  # GET /orgadmins/1
  # GET /orgadmins/1.json
  def show
  end

  # GET /orgadmins/new
  def new
    @organization = Organization.new
  end

  # GET /orgadmins/1/edit
  def edit
    @orgs = Organization.all
    @logo = Logo.new
    @fundtypes = FundingType.all
  end

  # POST /orgadmins
  # POST /orgadmins.json
  def create
    @organization = Organization.new(orgadmin_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orgadmins/1
  # PATCH/PUT /orgadmins/1.json
  def update
    respond_to do |format|
      if @organization.update(orgadmin_params)
        puts params[:name]
        puts @organization.name
        puts orgadmin_params
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orgadmins/1
  # DELETE /orgadmins/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to orgadmins_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def showorgconnections
    @fundingsents = FundingSent.select('"orgrcvd".name, "funding_types".fundtype').from('"funding_sents" INNER JOIN "organizations" "orgrcvd" ON "orgrcvd"."id" = "funding_sents"."organization_id_received" INNER JOIN "organizations" "orgsent" ON "orgsent"."id" = "funding_sents"."organization_id_sent" INNER JOIN "funding_types" ON "funding_types"."id" = "funding_sents"."funding_type_id"').where("funding_sents.organization_id_sent = ?", params[:id])
    
    results = []
    
    @fundingsents.each do |funding_sent|
      results.push([funding_sent.name, funding_sent.fundtype]);
    end

    render :json => results
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orgadmin
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orgadmin_params
      params.permit(:name, :email, :address, :phone, :id, :descrip)
    end
end

ruby/neighborhood_allies/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/neighborhood_allies/app/helpers/orgadmins_helper.rb
module OrgadminsHelper
end

ruby/neighborhood_allies/app/helpers/seed_gen_helper.rb
module SeedGenHelper
end

ruby/neighborhood_allies/app/views/orgadmins/_form.html.erb
<%= form_for(@organization, :html => {class: "container form-horizontal"},url: { action: 'create', controller: 'orgadmins'})  do |f| %>
  <%= render 'formcontrols' %>
    <div class="form-group row">
    <%= link_to 'Back', orgadmins_path, class: "btn btn-warning" %>
    <%= f.submit "Submit", class:"btn btn-success pull-right" %>
  </div>
<% end %>

ruby/neighborhood_allies/app/views/orgadmins/_formcontrols.html.erb
<!-- the logo code will go here -->
		
			<!-- org name field/ Perhaps this can already be filled in? -->
			<div class="form-group row">
				<label class="control-label col-md-1" for="usr" >Name</label>
				<div class = "col-md-8">
				<input type="text" class="form-control" placeholder="Neighborhood Allies" name="name" value="<%= @organization.name %>">
				</div>
			</div>
			
			<!-- description stuff-->
			<div class="form-group row">
				<label class="control-label col-md-1" for="descrip" >Description</label>
				<div class = "col-md-8">
				<textarea class="form-control" placeholder="This is a great non-profit doing work in..." name="descrip"><%= @organization.descrip %></textarea>
				</div>
			</div>
			
			<!-- email -->
			<div class="form-group row">
				<label class="control-label col-md-1" for="email">Email</label>
				<div class = "col-md-8">
					<input type="email" class="form-control" placeholder="organization@email.com" name="email" value="<%= @organization.email %>">
				</div>
			</div>				
			
			<!-- phone number - don't forget to add the dashes and figure out how
				line up the beginning-->
			<div class="form-group row">	
				<label class="control-label col-md-1" style="padding-right: 0px" for="phone">Phone</label>
				<div class="col-md-4">
				
						<input type="tel" name="phone" class="form-control" value="<%= @organization.phone %>" size="12" maxlength="12" required="required" title="" placeholder="555-555-5555">

				</div>
			</div>
			
			<!-- address stuff-->
			<div class="form-group row">
				<label class="control-label col-md-1" for="address" >Address</label>
				<div class = "col-md-8">
				<textarea class="form-control" placeholder="555 Liberty Ave" name="address"><%= @organization.address %></textarea>
				</div>
			</div>


  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

ruby/neighborhood_allies/app/views/orgadmins/_formedit.html.erb
<%= form_for(@organization, :html => {class: "container form-horizontal"},url: "/orgadmins/" + @organization.id.to_s)  do |f| %>
  <%= render 'formcontrols' %>
    <div class="form-group row col-md-9">
    <%= link_to 'Back', orgadmins_path, class: "btn btn-warning" %>
    <%= f.submit "Submit", class:"btn btn-success pull-right" %>
  </div>
<% end %>

ruby/neighborhood_allies/app/views/orgadmins/_logo.html.erb
<%= form_for(@logo, :html => {:multipart => true, :id => "edit_logo"},
				    :format => :json, 
				    :url => "/logos/",
				    :remote => true) do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :data %>
        <%= f.file_field :data %>
    </div>
    <%= f.collection_select :organization_id, @orgs, :id, :name, include_blank: true %>

<% end %>
        <a onClick="uploadPhoto()" href="#" class="btn btn-primary">Upload</a>
        
<script>
   function uploadPhoto(){
       console.log("starting upload");
       formData = new FormData()
       formData.append('logo', $('#logo_data')[0].files[0]);
       formData.append('organization_id', $('#logo_organization_id').val());
       formData.append('name', $('#logo_name').val());
       console.log(formData);
        $.ajax({
            url: "/logos/",
            type: "POST",
            processData: false,
            contentType: false,
            //data: {logo: {data: $("#logo_data"), organization_id: $("#logo_organization_id"), name: $("#logo_data")}},
            data: formData,
            success: function (data) {
                console.log("Success!");
                $("#edit_logo_img").attr('src', '/logos/<%= @organization.id %>/serve');
            },
            error: function (xhr, status, err) {
                console.log(status, err.toString());
            }
            
        })

        console.log("hello there!");
    }
</script>

ruby/neighborhood_allies/app/views/orgadmins/_orgconnections.html.erb
<script>
  var orgconnections = [];

  function showorgconnections(id) {
   	$.post("/orgadmins/"+id+"/showorgconnections", function(data)
   	{
  	  
  	  orgconnections = data;
  	  var contentstring = '';
  	  
  	  for (var i = 0; i < orgconnections.length; i++) {
  	    var orgconnection = orgconnections[i];
  	    
	      var line = {name: orgconnection[0], fundtype: orgconnection[1]};
	    
	      contentstring += '<tr><td>'+line.name+'  </td><td>'+line.fundtype+'</td></tr>';
  	  };
  	  
  	  document.getElementById("orgconnections").innerHTML = '<table>'+contentstring+'</table>';
  	  
   	});
  }
   
  function addfundtype(organizationid) {
    // $.post("/orgadmins/"+id+"/addorgconnections", function(data)
   	// {
   	
   	// }
     
    showorgconnections(organizationid); 
  }
 </script>

<br>
<br>
<h4> Company Connections</h4>
<div id="connections">
  
    <p id="orgconnections" class="orgconnections">
      <script>
      showorgconnections(<%= @organization.id %>)
      </script>
    </p>
</div>
<div id="newconnection">
  <select name="neworgconnectionname">
    <option value="" selected="selected">Please select an organization to link to:</option>
    <% @orgs.each do |organization| %>
      <option value="<%= organization.id %>"><%= organization.name %></option>
    <% end %>
  </select>
  <select name="neworgconnectionfundtype">
    <option value="" selected="selected">Please select the finding type to link to the organization:</option>
    <% @fundtypes.each do |fundtype| %>
      <option value="<%= fundtype.id %>"><%= fundtype.fundtype %></option>
    <% end %>
  </select>
  
  <a onClick="addfundtype(<%= @organization.id %>);" href="#" class="btn btn-primary">Add Connection</a>
  <br>
  <br>
</div>

ruby/neighborhood_allies/app/views/orgadmins/edit.html.erb
<div class="col-md-8 col-md-offset-2">
    <div class="panel">
      <img id="edit_logo_img" src="/logos/<%= @organization.id %>/serve" style="padding: 15px;max-width: 200px; max-height: 200px">
    <%= render 'formedit' %>
    </div>
    <%= render 'logo' %>
  
    <%= render 'orgconnections' %>
</div>

ruby/neighborhood_allies/app/views/orgadmins/index.html.erb
<div class="col-xs-12 admin-body">
<div class="container col-md-2 columns"></div>
<div class="container col-md-8" style="background-color: white">
<ul class="list-unstyled">
  	<% @organizations.each do |organization| %>
	<li>
		<div class="list-group-item clearfix">
		<div class="pull-left">
		  <img src="/logos/<%= organization.id %>/serve" class="admin-logo">		
		</div>
		<div>
			<h3 class="list-group-item-heading title"><%= organization.name %></h3>
			<p class="list-group-item-text"><%= organization.descrip %></p>
		</div>
		<span class="pull-right">
			<%= link_to 'View',organization_path(organization), class: 'btn btn-info' %>
			<%= link_to 'Edit', edit_orgadmin_path(organization), class:"btn btn-warning" %>
			<button class= "btn btn-success">Connections</button>
			<!--<%= link_to 'Connections',organization_path(organization), class: 'btn btn-success' %> -->
			<%= link_to 'Suspend', "#", class:"btn btn-danger" %>
		</span>
		</div>
	</li>
	<% end %>
 </ul>
</div>
</div>

ruby/neighborhood_allies/app/views/orgadmins/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="panel">
    <div class="panel-heading">New Organization</div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
  </div>
</div>

ruby/neighborhood_allies/app/views/orgadmins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_orgadmin_path(@orgadmin) %> |
<%= link_to 'Back', orgadmins_path %>